### ISSUE TITLE
\iff cause range error

### ISSUE THREAD

**Issue by gunnarmein-ts** [arnog/mathlive#2237]
## Description

latex \iff causes stack overflow

### Steps to Reproduce

- go to https://cortexjs.io/mathlive/demo/
- open debugger
- type '\iff' in latex field
- watch error in the debugger console

### Actual Behavior

crash, unexpected display

### Expected Behavior

should become "\Longleftrightarrow"

### Environment

> Is this a regression: did it use to work in a previous version?
worked correctly in 0.93.0

**MathLive version**  0.98.5
**Operating System** macOS Sonoma (also happens on github Ubuntu test runner)
**Browser** Chrome

**Comment by QuinnStraus** [comment]
Just independently discovered this bug as well, it worked for me in 0.98.4 but once I upgraded to 0.98.5 it crashed. I got one error that said "TypeError: window.MathfieldElement.isFunction is not a function" when calling the validateLatex utility on the field, if that helps in diagnosing the problem. 
I also noticed another problem with \iff in 0.98.4 where calling getValue("latex-expanded") on the mathfield would always add a "\;" space on either side of the \iff, which was slightly annoying and might also be related.
